name: Test Worfklow

on:
  push:
  
jobs:
  Explore-Workflows:
    runs-on: ubuntu-latest
    steps:

      - name: Hello world
        run: echo "Hello there, we are exploring workflows"

      - name: More infos
        run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
